### ISSUE TITLE
[Suggestion] Blocking the rotation/interaction of players with the map.

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/Maplands#13]
At the moment is it possible for players, to rotate a map from maplands, by simply right-clicking it in a item frame.
This is annoying and requires additional plugins like WorldGuard, to block it.
So it would be nice if maplands denies/blocks this action by default.

**Comment by bergerkiller** [comment]
This sounds reasonable and is easy to do (cancel click-to-rotate actions on the map), I'll consider adding it

**Comment by bbayu123** [comment]
Solved in bdc741b
You may check if https://ci.mg-dev.eu/job/Maplands/40/ works for you.

**Comment by Andre601** [comment]
@bbayu123 I mean bergerkiller noticed me about that in the PR ;P
