### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/Maplands#19]
I received those errors in the console: https://gist.github.com/Andre601/fea6362a916c54ec6fc7fc9ee2ee727c

I can't really tell, what exactly caused them.
One possible cause (at least for the very first one) could be that the map was loaded, after I renamed the world (server was offline during the reload.)

System info:
- Server: PaperMC 1.14.4
- Maplands v0.6, BKCommonLib v1.14.4-v1

**Comment by bergerkiller** [comment]
Unfortunately the gist expired by now, but enough changes were made since october I'm not sure if the problem even still exists. If it does, you can reopen it.
