### ISSUE TITLE
Server crashes when using Maplands in combination with SlimeWorldManager

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/Maplands#21]
This issue was also reported to https://github.com/Grinderwolf/Slime-World-Manager/issues/130 as the stacktrace(s) display `com.grinderwolf.swm` meaning it is most likely caused by SlimeWorldManager.

I still want to report it here too as you may find a work-around/fix for this issue.

**The issue**:
When using `/map` to create a map, while being in a world handled by the plugin SlimeWorldManager, does the Server crash with the following stacktraces:
https://gist.github.com/Andre601/07483eae201e94c2cfb8181e1661c6d3#file-latest-log

Here is the crash-report from that:
https://gist.github.com/Andre601/07483eae201e94c2cfb8181e1661c6d3#file-crash-report-txt

**Possible cause**:
My guess is that SWM removed or changed a method, which (temporary) stored information used in maps.
This was first discovered through BannerBoard, where the banners (Itemframes with maps) didn't display any images and only showed the texture of the empty Itemframe.

**Comment by bergerkiller** [comment]
SWM uses a custom implementation of WorldsServer (extends WorldServer) for their worlds, which includes code that I do not know about retrieving the value of a List (ArrayList in this case) that doesn't exist. Without knowing what code this is it is difficult for me to really see the cause for it.

That said, the map displays of maplands doesn't alter server state at all, since all of this logic is done using packets. The only thing I can think of might be that the metadata stored in the items in the map always refers to map id #0, which might not exist(?). I wonder if opening one vanilla empty map once on the world, then installing maplands, eliminates the crash

**Comment by Andre601** [comment]
I tried that.
- Stopped server
- Removed Maplands (v0.7)
- Started server
- Created a vanilla map
- Stopped server
- Re-installed Maplands
- Started server
- Created a vanilla map again (SWM doesn't save inventories)
- Run `/map`
- Server crash.

Like I mentioned is that for sure an issue on SWMs end as the plugin seems to be unable to handle something specific (perhaps the packets you send?)
And I assume that BannerBoard experiences the same issues, but maybe just fails silently instead of doing something that causes the crash...

**Comment by bergerkiller** [comment]
Oh wait, so it crashes before you put the item into an itemframe? That is quite interesting. SWM not saving inventories is unfortunate, because otherwise you could check if merely holding the item (without bkcommonlib/maplands even installed) causes a server crash

**Comment by Andre601** [comment]
I don't think this would work as SWM worlds are saved differently than normal worlds and in their own folder.
So a vanilla world is incompatible with SWM unless I would import it, but this would probs make the world lose specific data like the inventory of a player.

And yes, the crash happens when just running the command and retrieving the map. I can see that the map is added to my inventory before I get disconnected.

The goal of SWM is to reduce storage space of worlds by handling it differently and also storing only data needed (like the blocks of a world),

Maybe this could help a bit: SWM requires you to install and use a class-modifier jar, which you define as a java agent in the startup params, so that it can modify the server in a way to allow the storage and use of the slime worlds.

**Comment by bergerkiller** [comment]
When I get home Ill prepare a test version of BKCommonLib that disables the initialization of the map display, to see if this crash is only caused by the item in the inventory or not. If that is the case, it is definitely an issue only SWM can fix

**Comment by bergerkiller** [comment]
https://www.dropbox.com/s/2fa1lgfw9l6t45b/BKCommonLib-1.15.1-v1-SNAPSHOT.jar?dl=0 can you see if it also crashes with this version? Maplands wont work and map will stay empty, but /map should work fine

**Comment by Andre601** [comment]
I tested it and the server also crashes with the changed BkCommonLib

**Comment by bergerkiller** [comment]
Then for sure what BKCommonLib does with packets has little to do with it. It's simply that particular item that SWM cannot handle, so it's something they will need to fix on their end

**Comment by bergerkiller** [comment]
I may have found the problem that caused SWM to crash, and fixed it https://github.com/bergerhealer/BKCommonLib/commit/2e57ddd775f0194f15c62be94aeb746ba5c18475

It had no effects on vanilla, but I guess it caused an NPE in SWM. It's worth checking to see if the crash is now fixed. https://ci.mg-dev.eu/job/BKCommonLib/703/

**Comment by Andre601** [comment]
This seems to have fixed it!

Thanks a lot.
