### ISSUE TITLE
Get world block from clicked display?

### ISSUE THREAD

**Issue by PikaMug** [bergerhealer/Maplands#22]
I'd like to get the actual overworld Block depicted within a framed map. One of many failed attempts:

```java
@EventHandler
public void onMapClick(MapClickEvent evt) {
    int x = evt.getX();
    int y = evt.getY();
    World world = evt.getItemFrame().getWorld();
    if (evt.getDisplay() instanceof TestFrameMap) {
        TestFrameMap frameMap = (TestFrameMap)evt.getDisplay();
        Block b = frameMap.getBlockAt(x, y).toBlock(world);
        System.out.println("You clicked on " + b.getType().name());
    }
}
```
What is the correct way of doing this? Thanks for creating another fascinating resource!

**Comment by bergerkiller** [comment]
The x and y are pixel coordinates on the map. You need to the following things:

1. Get the start block, 'facing' direction and zoom level of a maplands map (TestFrameMap) 
These fields are unfortunately private so you'll have to use reflection:
```
    private ZoomLevel zoom;
    private BlockFace facing;
    private Block startBlock;
```
2. Get the drawn 'depth' at the coordinates clicked (display.getLayer().getDepth(x, y))

3. Convert screen coordinates (your x/y) to tile coordinates using screenToTile. Clicked x is x, clicked y is z and depth is y.
https://github.com/bergerhealer/Maplands/blob/master/src/main/java/com/bergerkiller/bukkit/maplands/ZoomLevel.java#L129

4. Convert tile coordinates to the relative block coordinates, making use facing.
screenTileToBlock: https://github.com/bergerhealer/Maplands/blob/master/src/main/java/com/bergerkiller/bukkit/maplands/MapUtil.java#L51

5. Add start block coordinates to the result of that function

You may have to experiment with the depth +1 or -1, I'm not sure what will work for you exactly.

**Comment by bergerkiller** [comment]
If you got something that works I will happily add it to Maplands itself. I do have to rename TestFrameMap at some point, the plugin isn't really written with an api in mind

**Comment by PikaMug** [comment]
TestFrameMap#getBlockAt effectively took care of 1-4, but I did neglect step 5. Fixing that net me a correct X coordinate, but the Y and Z still came back wrong. So, I tried recreating your steps more precisely (no need for reflection)...

```java
@EventHandler
public void onMapClick(MapClickEvent evt) {
    MapDisplay display = evt.getDisplay();
    
    if (display instanceof TestFrameMap) {
        MapDisplayProperties properties = new MapDisplayProperties(display);
        BlockFace facing = properties.get("facing", BlockFace.NORTH_EAST);
        int startX = properties.get("px", 0);
        int startY = properties.get("py", 0);
        int startZ = properties.get("pz", 0);
        
        IntVector3 tile = ((TestFrameMap)display).getTileAt(evt.getX(), evt.getY());
        IntVector3 block =  MapUtil.screenTileToBlock(facing, tile).add(startX, startY, startZ);
        
        Block real = evt.getItemFrame().getWorld().getBlockAt(block.x, block.y, block.z);
        System.out.println(evt.getPlayer().getName() + " clicked on " + real.getType().name() + " at x=" 
                + real.getX() + ", y=" +  real.getY() + ", z=" + real.getZ());
    }
}
```

...but I'm still getting correct X, wrong Y/Z. Any idea what's happened?

**Comment by bergerkiller** [comment]
My guess is that the depth may be wrong, so its picking a block one too deep or one too far up. Try writing that getTileAt manually (see the code in TestFrameMap) and add/substract a value from the result of getDepth(x,y)

I dont think getBlockAt is used for anything, so it's not tested and may have bugs. I forgot it existed

**Comment by PikaMug** [comment]
While doing that did allow me to dial in the Y value (a depth of +14 for zoom level 16), there was no way to adjust Z independently (which was still incorrect). I also wasn’t sure how to calculate the new amount to add when changing zoom, as +14 was no longer correct.

I’m confident I’ve done something wrong, so I’ll come back to this after some rest.

**Comment by bergerkiller** [comment]
Unfortunately I don't know much more that I can say to help you, but if you can't figure out a solution I can spend some time to write a getBlock(x, y) that works (and returns world coordinates rather than relative). Those honeycomb coordinate spaces are complex so I understand you've got some problems with it.

**Comment by PikaMug** [comment]
That would be stellar even if I do get this working. No doubt it’d add a ton of new possibilities for this. Personally I was thinking of making a SimCity-like game with it :)

**Comment by PikaMug** [comment]
So I've discovered that using a 3x3 grid of framed maps for testing was a bad idea. Neither my code nor these parts of the plugin seem to account for anything larger than a single map. Oops.

Now that I'm using a single map, I've had some success dialing in values. Depth alone still wasn't enough - here's what I've come up with:

```java
@EventHandler
public void onMapClick(MapClickEvent evt) {
    MapDisplay display = evt.getDisplay();
        
    if (display instanceof TestFrameMap) {
        MapDisplayProperties properties = new MapDisplayProperties(display);
        BlockFace facing = properties.get("facing", BlockFace.NORTH_EAST);
        ZoomLevel zoom = properties.get("zoom", ZoomLevel.DEFAULT);
        int startX = properties.get("px", 0);
        int startY = properties.get("py", 0);
        int startZ = properties.get("pz", 0);

        IntVector3 tile = ((TestFrameMap)display).getTileAt(evt.getX(), evt.getY());
        IntVector3 block =  MapUtil.screenTileToBlock(facing, tile).add(getOffset(zoom, startX, startY, startZ));
            
        Block real = evt.getItemFrame().getWorld().getBlockAt(block.x, block.y, block.z);
        System.out.println(evt.getPlayer().getName() + " clicked on " + real.getType().name() + " at x=" 
                    + real.getX() + ", y=" +  real.getY() + ", z=" + real.getZ());
    }
}
     
public IntVector3 getOffset(ZoomLevel zoom, int x, int y, int z) {
    switch(zoom.getWidth()) {
    case 4:
        return new IntVector3(x + 9, y + 21, z + 25); // Misaligned
    case 8:
        return new IntVector3(x + 3, y + 10, z + 13); // Misaligned
    case 16:
        return new IntVector3(x + 2, y + 4, z + 6); // Precise
    case 32:
        return new IntVector3(x + 1, y + 2, z + 3); // Precise
    case 64:
        return new IntVector3(x + 0, y + 1, z + 2); // Misaligned
    default:
        return new IntVector3(x, y, z);
    }
}
```

Paying special attention to #getOffset, the +N adjustments I've found through trial-and-error work _perfectly_ for ZOOM16 and 32, although I'd still have to find out how to size up for grids. The other cases don't, however, with the issue seemingly being precision. For example, 64 seems to shift blocks roughly one third of a block on the x axis and nearly an entire block on the z. Case 4 and 8 behave similarly, but less noticeably due to the scale.

I'm attributing this to loss of precision somewhere, which I suspect is from use of IntVector3. Looking at the class, I'm curious why you've opted to make your own? Bukkit's Vector does most of these operations and can be instantiated with integers or doubles. Going down the line, I already see some loss here: https://github.com/bergerhealer/Maplands/blob/0a65a15acea8a74ddc5aefd62d1a214e31b87369/src/main/java/com/bergerkiller/bukkit/maplands/ZoomLevel.java#L34

**Comment by bergerkiller** [comment]
Vector3 is immutable, Bukkit's Vector class is mutable. Theres also some historical Vector3f nonsense, which uses float rather than double precision for supposed faster calculations. I assumed back then that for map display 3d model rendering, using a single precision float was more than adequate for the matrix transformation maths, but I was wrong. IntVector3 exists because well, its int, and also immutable. It avoids needless flooring/int casting all over the place, and makes for-iteration and hashtable lookups more efficient.

Immutable is desirable because then you don't need defensive copying to protect against cases like:
1. User calls setPosition(vector)
2. User modifies vector (adds 1 to y)
3. User calls setPosition(vector) on another object
4. Giant mess ensues when positions are modified in either object, as they now share the same position.

The maths in ZoomLevel are fine for what it tries to do, but it's based mainly on tiling characteristics. You probably should not be using the zoom level width / float math in general.

**Comment by bergerkiller** [comment]
I think I need to write some tests for the screen -> tile coordinate space maths. The reverse is available and works (it renders fine), so I got a way to validate the output already. I'll see what I can do to fix this

**Comment by PikaMug** [comment]
That makes sense - I think WorldEdit has their BlockVector3 for the same reasons. Of course, they aren't converting anything to/from a 2D plane, but I digress.

I'd appreciate those tests, but I understand this isn't high priority at the moment. In the meantime, would it be possible to create/expose a way to get the 2D tile coordinates of the framed map being clicked on, if present? It looks as though Maplands processes all blocks in view even if they don't end up on the final product, so if I could programmatically get the tile of a known block (again, assuming it's present since the map can be AWSD-scrolled), then I could just get the difference between that and the clicked tile and translate that into overworld vectors.

**Comment by bergerkiller** [comment]
> if I could programmatically get the tile of a known block

Those methods exist and work much more reliably, as those are also used for rendering. Make it into relative coordinates, then use blockToScreenTile.

https://github.com/bergerhealer/Maplands/blob/master/src/main/java/com/bergerkiller/bukkit/maplands/TestFrameMap.java#L195

**Comment by bbayu123** [comment]
> I do have to rename the TestFrameMap class at some point, the plugin isn't really written with an api in mind.

The thing is, if you rename a class that extends MapDisplay, all existing maps stop working, at least for me. Many many times I have renamed or relocated a class, and every single map needs to be replaced.

**Comment by bergerkiller** [comment]
@bbayu123 I could get around it for now by making another class and keep TestFrameMap, which extends that one but is otherwise empty

**Comment by bbayu123** [comment]
> @bbayu123 I could get around it for now by making another class and keep TestFrameMap, which extends that one but is otherwise empty

I mean, that short term solution doesn't really address the core problem of "renaming stuff breaks things", but I guess there isn't a better solution that's easy to execute is there.

**Comment by PikaMug** [comment]
How's this look? Like an earlier attempt, I'm getting a correct X value, but wrong Y/Z.

```java
@EventHandler
    public void onMapClick(MapClickEvent evt) {
        MapDisplay display = evt.getDisplay();
        
        if (display instanceof TestFrameMap) {
            MapDisplayProperties properties = new MapDisplayProperties(display);
            BlockFace facing = properties.get("facing", BlockFace.NORTH_EAST);
            int startX = properties.get("px", 0);
            int startY = properties.get("py", 0);
            int startZ = properties.get("pz", 0);
            String worldName = properties.get("mapWorld", "");
            if (worldName.length() == 0) {
                Player player = evt.getPlayer();
                worldName = player.getWorld().getName();
                startX = player.getLocation().getBlockX();
                startY = player.getLocation().getBlockY();
                startZ = player.getLocation().getBlockZ();
                properties.set("px", startX);
                properties.set("py", startY);
                properties.set("pz", startZ);
                properties.set("mapWorld", worldName);
            }
            World startWorld = Bukkit.getWorld(worldName);
            Block startBlock = startWorld.getBlockAt(startX, startY, startZ);
            
            World world = evt.getItemFrame().getWorld();
            Block b = world.getBlockAt(evt.getItemFrame().getLocation());
            int bx = b.getX();
            int by = b.getY();
            int bz = b.getZ();
            
            if (world == startWorld /*&& this.blockBounds.contains(bx, by, bz)*/) {
                int dx = bx - startBlock.getX();
                int dy = by - startBlock.getY();
                int dz = bz - startBlock.getZ();
                IntVector3 mapTile = MapUtil.blockToScreenTile(facing, dx, dy, dz);
                System.out.println("Internal framemap tile of x=" + mapTile.x + " y=" + mapTile.y + " z=" + mapTile.z);
                
                IntVector3 clickedTile = ((TestFrameMap)display).getTileAt(evt.getX(), evt.getY());
                System.out.println("Internal clicked tile of x=" + clickedTile.x + " y=" + clickedTile.y + " z=" + clickedTile.z);
                
                IntVector3 direction = mapTile.subtract(clickedTile);
                IntVector3 sum = new IntVector3(b.getLocation()).add(direction);
                Block real = world.getBlockAt(sum.x, sum.y, sum.z);
                System.out.println("Found overworld " + real.getType().name() + " at x=" 
                        + real.getX() + ", y=" +  real.getY() + ", z=" + real.getZ());
            }
        }
    }
```
Think I'll have to call it quits for now. Looking forward to seeing where you take this!

And personally, I would just rename TestFrameMap at 1.0 and explain that it's not compatible with earlier versions in the release notes.

**Comment by bergerkiller** [comment]
RE: TestFrameMap.

If I rename TestFrameMap to MaplandsDisplay, then add this class:
`public final class TestFrameMap extends MaplandsDisplay {}`

Then old maps will continue working just fine, and you can still use getMapDisplay(MaplandsDisplay.class) or use casting. Obviously you shouldn't use TestFrameMap as an api anymore, that will break the plugin.

The problem in your code I spot is your assumption that you can simply subtract tiles to adjust for differences, but it's not that simple sadly. Some tiles don't even exist. Mapping hexagon tiles on a 2D grid is impossible, and for that reason there are a lot of points on this grid that don't have tiles at a particular y-coordinate (depth). Just imagine cutting out loads of hexagons out of paper and stacking them together. Then take your stack and shift it slightly up/down/left/right. Now you got all possible positions a hexagon can have, and can create any isometric view of cubes.

Sadly I don't have good visualizations of this

**Comment by bergerkiller** [comment]
Sorry for the long delay

I've made some changes, such as swapping x and z coordinates everywhere because it was very confusing. Z is now depth, rather than the vertical position on the map.

I had to fix the screenToTile function because it was broken for negative x/y screen coordinates. I also noticed that the coordinates were relative to the center (subtracts half display width/height when drawing), which may have caused the strange outputs you had.

There is now a public getBlockAt(x, y) function in MaplandsDisplay (TestFrameMap should no longer be used, I renamed it) which will give you the block drawn at those coordinates of the display.

https://github.com/bergerhealer/Maplands/commit/e311d9a0dffe6705be4e850c2c18203a057c7af3

https://ci.mg-dev.eu/job/Maplands/47/

**Comment by PikaMug** [comment]
Not at all - I appreciate the swift response.

The swap appears to be for the best, although I understand your previous rationale. Those coordinate issues would indeed explain a lot, thank you.

As far as I can tell, #getBlockAt is working on all zoom levels and with any size grid. I occasionally get a return type of AIR, the coordinates of which vary slightly depending on the map facing, but they're always close enough that I could just find the nearest block within a radius.

Can't wait to start playing around, and seeing what the community can do with this resource. You've outdone yourself! :)

**Comment by bergerkiller** [comment]
The air thing I noticed too. I think it's caused by a slight mismatch, so it has the depth for one block and the tile coordinates of another, resulting in the wrong block being returned. I might fix that at some point by having a better pixel coordinates -> tile coordinates function, but you shouldn't have problems from having a more precise method. :)
