### ISSUE TITLE
Writing marker name opens anvil gui for other players too

### ISSUE THREAD

**Issue by FalloutBe** [bergerhealer/Maplands#24]
Tested on paperMC 1.18.1-152
Doesn't always happen, but still quite often other players tell me there's a strange anvil GUI popping up when I'm writing new markers.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/1219/ See if this makes a difference. It was indeed opening for everyone viewing the display, instead of the ones controlling it.

**Comment by bbayu123** [comment]
Closing issue, fixed as explained above. It is impossible to only limit the anvil to only open for the one single player who clicked, so this is the best compromise.
