### ISSUE TITLE
Recoucepacks

### ISSUE THREAD

**Issue by Huiqqqqqq** [bergerhealer/Maplands#27]
I have questions about the texture pack... I don't understand how to load my texture pack?

**Comment by bergerkiller** [comment]
If the texture pack is configured in server.properties then maplands should automatically pick that up. This involves hosting your texture pack with a static URL, like using dropbox or a ftp server or some other host.

**Comment by bbayu123** [comment]
Closing issue, question answered - it will load if you place it inside your `server.properties` file.
