### ISSUE TITLE
Blocks not rendering below y=0

### ISSUE THREAD

**Issue by MilanvanDriel** [bergerhealer/Maplands#29]
Hi there!

I just came across this amazing plugin and instantly installed it on my minecraft server where I am building some stuff with friends.
We are building on a big stone plateau that's quite low to the ground. I noticed that when I was rendering the map I could only see the top parts of the buildings we made.
So the map is not rendering anything y=0 or below.
Since we've done some things with command block coordinates, we cannot just move everything up a few blocks so that it renders correctly. So if this could be fixed that would be awesome!
Love your work!

Cheers,
- Milan

**Comment by bergerkiller** [comment]
Ill try to look into it, its probably some lower bound of a loop that I never changed after mojang added < 0 worldgen

**Comment by bbayu123** [comment]
Closing issue, workaround suggested with resolution confirmed.
