### ISSUE TITLE
Use existing map renders from other programs like Dynmap, Overviewer, Mapcrafter

### ISSUE THREAD

**Issue by Phoenix616** [bergerhealer/Maplands#5]
It would be nice if the map could view already rendered images by other programs like Dynmap, Overviewer and Mapcrafter. That way you wouldn't have to render the world twice for web and ingame maps and making it possible to use this plugin on larger servers too.

**Comment by bergerkiller** [comment]
Maplands depends on the block data itself to do the rendering. It needs to know the block material types and their data, and potentially in the future, tile entity data too. I don't think world mapper programs like that keep such information cached.

However, canvases are just simple surfaces to draw on. A plugin to display Dynmap on maps, by using their API, would be something that is feasible.

**Comment by Phoenix616** [comment]
@bbayu123 not really a duplicate of that. This idea was about using existing rendered maps ingame, not displaying the Maplands map online.

**Comment by bbayu123** [comment]
Oh, is that so? Then as berger has mentioned, a plugin that draws on the canvas will already do the trick. This is outside the scope of what Maplands offers.
